pipeline {
    agent any

    tools {
        maven 'maven1'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Code Quality') {
            steps {
                echo 'Quality of code..'
            }
        }
        stage('Deploy to Dev') {
            steps{
                echo 'dev..'
            }
        }
        stage('Deploy to Test') {
            steps {
                echo 'Test..'
            }
        }
        stage('Deploy to UAT') {
            steps{
                echo 'UAT..'
            }
        }
        stage('Deploy to pre_prod'){
            steps{
                echo 'pre_prod..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
            post {
                failure{
                    echo 'sending notification'
                }
            }
        }
    }
     post {
        always {
            echo 'One way or another, I have finished'
            deleteDir() /* clean up our workspace */
        }
        success {
            echo 'I succeeded!'
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            mail to: 'team@example.com',
             subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
             body: "Something is wrong with ${env.BUILD_URL}"
        }
        changed {
            echo 'Things were different before...'
        }
    }
}  
