pipeline {
    agent any

    tools {
        maven 'maven1'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Code Quality') {
            steps {
                echo 'Quality..'
            }
        }
        stage('Deploy to Dev') {
            steps{
                echo 'dev..'
            }
        }
        stage('Deploy to Test') {
            steps {
                echo 'Test..'
            }
        }
        stage('Deploy to UAT') {
            steps{
                echo 'UAT..'
            }
        }
        stage('Deploy to pre_prod'){
            steps{
                echo 'prod..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
